### ISSUE TITLE
Mauvais encodage des caractères dans la doc

### ISSUE THREAD

**Issue by voodoos** [voodoos/Projet_Simulateur_IGOSAT#1]
Visual studio enregistre ses fichiers en ANSI, doxigen, même réglé sur ISO-8859-15 génère un HTML sans les bons caractères....

**Comment by jbyunes** [comment]
Est-ce qu'on peut avoir un HTML généré pour voir d'où vient le problème, ils peuvent être à différents niveaux!
- la saisie peut-être faite dans un encodage
- le générateur peut transcoder dans un autre
- le document généré ne contient pas les bonnes infos d'encodage même si le document est correctement encodé
- le navigateur se trompe d'encodage pour afficher.

JBY

Le 19 févr. 2014 à 17:37, Ulysse notifications@github.com a écrit :

> Visual studio enregistre ses fichiers en ANSI, doxigen, même réglé sur ISO-8859-15 génère un HTML sans les bons caractères....
> 
> —
> Reply to this email directly or view it on GitHub.

## 

M. Jean-Baptiste Yunès
http://www.liafa.univ-paris-diderot.fr/~yunes/

**Comment by voodoos** [comment]
Le html généré est versionné. Dans le répertoire IGOsim/Doc.

En revanche ne vous en faites pas, je n'ai pas vraiment pris le temps de creuser. C'était surtout une bonne excuse pour tester le gestionnaire de bugs de GitHub.

Cdt,
Ulysse

**Comment by voodoos** [comment]
D'ailleurs on voit clairement un soucis dans le index.html : 
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>

Le navigateur attend de l' UTF-8, mais il est peut probable que Doctrine s'occupe de convertir l'ANSI en UTF8.

**Comment by jbyunes** [comment]
Ok on verra ça plus tard. Je ne suis pas sur paris cette semaine.

JBY

Le 20 févr. 2014 à 01:11, Ulysse notifications@github.com a écrit :

> D'ailleurs on voit clairement un soucis dans le index.html : 
> 
> Le navigateur attend de l' UTF-8, mais il est peut probable que Doctrine s'occupe de convertir l'ANSI en UTF8.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

M. Jean-Baptiste Yunès
http://www.liafa.univ-paris-diderot.fr/~yunes/

## 

M. Jean-Baptiste Yunès
http://www.liafa.univ-paris-diderot.fr/~yunes/

**Comment by voodoos** [comment]
Tout passé en UTF-8 (comme on aurait pu espérer que VC++ le fasse dès le début...). Y'a plus problème.
