### ISSUE TITLE
Format de messages

### ISSUE THREAD

**Issue by VladislavFitz** [voodoos/Projet_Simulateur_IGOSAT#10]
On a décidé que chaque message peut contenir une seule donné, par exemple le message de BatteryController "actualVoltage" doit être de type "double". Dans notre implémentation courante le payload de message est std::string. Ce serait logique d'utiliser templates, mais si on l'utilise on aura les modules/sockets/connexions qui ne reconnaît qu'un seul type de messages. Comment organiser les Messages alors?
Je pense de l'héritage de classe Message avec des types différentes: int, float, string pour commencer.

**Comment by voodoos** [comment]
![2014-03-18 22 12 26](https://f.cloud.github.com/assets/5031221/2453834/6e89a4c4-aee2-11e3-8509-fc8d4dc5acd9.jpg)

**Comment by VladislavFitz** [comment]
C'est exactement ça ce que j'ai écrit à la fin. Je l'implémente alors.

**Comment by voodoos** [comment]
Ça marche, moi je suis hors jeu jusqu'à ce weekend.
