### ISSUE TITLE
Surcharge d'opérateur [] de Module 

### ISSUE THREAD

**Issue by VladislavFitz** [voodoos/Projet_Simulateur_IGOSAT#11]
On a pensé que c'est soit une bonne idée de surcharger l'opérateur [] de Module pour ça qu'on peut choisir un socket par leur nom (par exemple Battery["toBatteryController"]). Mais on pourrait l'utiliser aussi pour avoir l'accès au paramètres de Module (par exemple Battery["Voltage"]). De toute façon, il nous reste encore des '()' à surcharger :) Qu'est-ce qu'on va faire?

**Comment by voodoos** [comment]
Finalement pas plus élégant à cause des pointeurs, on garde les getMachinByName
