### ISSUE TITLE
Quid des stimuli extèrieurs et de la simulation physique ?

### ISSUE THREAD

**Issue by voodoos** [voodoos/Projet_Simulateur_IGOSAT#5]
Exemples:
- Décharge / charge de la batterie au cours du temps
- Changement de position du satellite
  ...

Est-ce qu'on abstrait la notion de changement de paramètres d'un module depuis la simulation physique ? Avantages: vérif à la compilation, désavantage: plus complexe et surtout mélange les parties physique / simuation architecture abstraite
Ou en dur pour chaque module ?

**Comment by VladislavFitz** [comment]
Simulation physique pour chaque module? Je trouve qu'on doit se concentrer sur la simulation des entrailles de satellite. Je trouve que le problème avec simulation c'est ce que l'environnement doit aussi se changer en fonction de l'activité de la satellite (virage, levage e.t.c)
En ce qui concerne la batterie, on peut la simuler juste comme une fonction de temps (peut-être pas linéaire) ou tenir compte la perte de capacité à cause de changement de température e.t.c. Ça peut être difficile.

**Comment by voodoos** [comment]
Je pense qu'il faut qu'on raffine nos modules:

Des modules abstraits Capteurs et Actionneurs, avec des attributs et des méthodes spécifiques que saura utiliser une classe Environnement ou Simulation physique.

De plus colin a remarqué le fait que tous les modules n'auront pas forcément besoin de mémoire (les actionneurs par exemple). Peut-être qu'il serait plus "propre" d'enlever la mémoire de notre classe module et de faire une classe ModuleWithMemory qui rajoute ce qui est nécessaire.

Qu'en penses-tu ?

---

"En ce qui concerne la batterie, on peut la simuler juste comme une fonction de temps (peut-être pas linéaire) ou tenir compte la perte de capacité à cause de changement de température e.t.c. Ça peut être difficile." -> Ça c'est pas notre job :-p

**Comment by VladislavFitz** [comment]
Je comprends pas trop qu'est-ce que ça veut dire Capteurs et Actionneurs. Quelle est la différence?

**Comment by voodoos** [comment]
Ok voilà comment je vois la chose (commit c55fdb8b1e48698c3b4909270edd63a294a7d557) :

http://voodoos.github.io/Projet_Simulateur_IGOSAT/UML/thirdStepWithRetroaction.pdf

On rajoute simplement des paramètres avec leurs getters et setters. Ceux-ci seront accessible aux différentes rétroactions pilotées par le Timer.

Tout simplement non ?

Je pense même que l'on peut directement mettre les getter/setters/parameters dans Module, suffit de ne pas les utiliser pour les modules qui n'en ont pas besoin.

(le problème avec le rajout de modules particuliers c'est que après faut raffiner entre macromodules avec/sans parameters etc...)
