### ISSUE TITLE
Une bibliothèque utile? 

### ISSUE THREAD

**Issue by VladislavFitz** [voodoos/Projet_Simulateur_IGOSAT#7]
J'ai trouvé cela...
http://fr.wikipedia.org/wiki/SystemC
http://www.asic-world.com/systemc/tutorial.html
Et il me semble qu'on essaie d'implementer notre propre version de cette bibliothèque ;)
De toute façon c'est en C++ et on peut l'intégrer.

**Comment by voodoos** [comment]
En gros c'est le même genre d'outil que SCADE mais version texte uniquement non ?
Ça à l'air très bas niveau..

**Comment by VladislavFitz** [comment]
Comme j'ai compris, ça permet de travailler aussi bien au bas niveau, qu'au haut niveau. Mais je connais pas les détails, je suis en train de lire la documentation.

**Comment by voodoos** [comment]
Un capteur permet de récupérer une info de l'environnement (température ext, charge batterie...)
Un actionneur c'est un moyen qu'à le satellite de modifier son environnement (augmenter voltage batterie, allumer moteur, etc.)

**Comment by jbyunes** [comment]
Oui c'est une bonne idée que de regarder SystemC. J'avais oublié l'existence de ce truc...

JB

Le 2 mars 2014 à 00:30, Ulysse notifications@github.com a écrit :

> Un capteur permet de récupérer une info de l'environnement (température ext, charge batterie...)
> Un actionneur c'est un moyen qu'à le satellite de modifier son environnement (augmenter voltage batterie, allumer moteur, etc.)
> 
> —
> Reply to this email directly or view it on GitHub.

## 

M. Jean-Baptiste Yunès
http://www.liafa.univ-paris-diderot.fr/~yunes/
